RELEASE_TYPE: patch

Fixed an internal error when ``given()`` was passed a lambda.
